/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type FileExposeType = "PRESIGN" | "PRIVATE" | "PUBLIC";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MessageRole = "assistant" | "user";

export type MessageStatus = "DEAD" | "FAIL" | "INVALID_PAYLOAD" | "SUCCESS";

export type UsersStatus = "ACTIVE" | "INACTIVE";

export interface Accounts {
  created_at: Generated<string>;
  id: string;
  last_signed_in_at: string | null;
  password: string;
  updated_at: Generated<string>;
  username: string;
}

export interface Conversations {
  created_at: Generated<string>;
  id: string;
  title: Generated<string>;
  updated_at: Generated<string>;
  user_id: string;
}

export interface EmailVerificationTokens {
  created_at: Generated<string>;
  expires_at: string;
  id: string;
  token_hash: string;
  user_id: string;
}

export interface FinancialData {
  company: string;
  gross_profit: string | null;
  net_income: string | null;
  operating_income: string | null;
  revenue: string | null;
  sector: string;
  ticker: string;
  year: number;
}

export interface Messages {
  content: string;
  conversation_id: string;
  cost_usd_micros: Generated<string>;
  created_at: Generated<string>;
  id: string;
  role: MessageRole;
  stopped: Generated<boolean>;
  tool_call: Json | null;
}

export interface MessageTasks {
  attempts: Generated<number>;
  created_at: Generated<string>;
  exchange_name: string;
  expire_at: string;
  id: string;
  last_error: string | null;
  max_attempts: Generated<number>;
  message_status: MessageStatus;
  payload: Json;
  queue_name: string;
  updated_at: Generated<string>;
}

export interface Sessions {
  account_id: string;
  created_at: Generated<string>;
  device_uid: string;
  expire_at: string;
  id: string;
  info: Json;
  revoke_at: string | null;
  token_hash: string;
}

export interface StoredFiles {
  checksum: string | null;
  created_at: Generated<string>;
  expire_at: string | null;
  extension: string;
  file_expose_type: Generated<FileExposeType>;
  filename: string;
  filesize_byte: string;
  id: string;
  key_path: string;
  mime_type: string;
  owner_id: string;
  owner_table: string;
  presign_url: string;
  ref_name: string;
  storage_name: Generated<string>;
  updated_at: Generated<string>;
}

export interface Users {
  account_id: string;
  email: string;
  email_verified_at: string | null;
  first_name: string;
  id: string;
  last_name: string;
  user_status: Generated<UsersStatus>;
}

export interface DB {
  accounts: Accounts;
  conversations: Conversations;
  email_verification_tokens: EmailVerificationTokens;
  financial_data: FinancialData;
  message_tasks: MessageTasks;
  messages: Messages;
  sessions: Sessions;
  stored_files: StoredFiles;
  users: Users;
}
